export const sideBarData = [
  {
    routeLink: 'add-job',
    icon: 'fal fa-id-card',
    label: 'Add New Job',
    requiredPrivilege: true,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'add-employee',
    icon: 'fa fa-user-plus',
    label: 'Add New Employee',
    requiredPrivilege: true,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'interview-hub',
    icon: 'fa-solid fa-laptop-code',
    label: 'Interview Hub',
    requiredPrivilege: false,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'settings',
    icon: 'fal fa-cog',
    label: 'Settings',
    requiredPrivilege: true,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'referral',
    icon: 'fal fa-solid fa-handshake',
    label: 'Referal',
    requiredPrivilege: false,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'your-jobs',
    icon: 'fa-solid fa-briefcase',
    label: 'Your Jobs',
    requiredPrivilege: false,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'designation',
    icon: 'fa-solid fa-ranking-star',
    label: 'Designation',
    requiredPrivilege: true,
    requiredSpecialPrivilege: false,
  },
  {
    routeLink: 'jobOffered',
    icon: 'fa-solid fa-envelope-open-text',
    label: 'Job Offered',
    requiredPrivilege: true,
    requiredSpecialPrivilege: true,
  },
  {
    routeLink: 'allEmployees',
    icon: 'fas fa-users',
    label: 'Employees',
    requiredPrivilege: true,
    requiredSpecialPrivilege: true,
  },
];